---
- name: pruebas de implementacion de hardening en ambiente local
  hosts: all
  become: true
  gather_facts: true  
  tasks:

    - name: extraer informacion de la version
      ansible.builtin.command: "cat /etc/redhat-release"
      register: os_release

    - name: ejecutar hardening rhel 8
      include_tasks: playbook-rhel8.yml
      when: "'8' in os_release.stdout"

    - name: ejecutar hardening rhel 9
      include_tasks: playbook-rhel9.yml
      when: "'9' in os_release.stdout"