---
- name: Disable SSH Access via Empty Passwords
  block:
    - name: Disable SSH Access via Empty Passwords
      block:

      - name: Check for duplicate values
        lineinfile:
          path: /etc/ssh/sshd_config
          create: true
          regexp: (?i)^\s*PermitEmptyPasswords\s+
          state: absent
        check_mode: true
        changed_when: false
        register: dupes

      - name: Deduplicate values from /etc/ssh/sshd_config
        lineinfile:
          path: /etc/ssh/sshd_config
          create: true
          regexp: (?i)^\s*PermitEmptyPasswords\s+
          state: absent
        when: dupes.found is defined and dupes.found > 1

      - name: Insert correct line to /etc/ssh/sshd_config
        lineinfile:
          path: /etc/ssh/sshd_config
          create: true
          regexp: (?i)^\s*PermitEmptyPasswords\s+
          line: PermitEmptyPasswords no
          state: present
          insertbefore: BOF
          validate: /usr/sbin/sshd -t -f %s
      when: ansible_virtualization_type not in ["docker", "lxc", "openvz", "podman", "container"]
      tags:
      - CCE-80896-4
      - CJIS-5.5.6
      - DISA-STIG-RHEL-08-020330
      - NIST-800-171-3.1.1
      - NIST-800-171-3.1.5
      - NIST-800-53-AC-17(a)
      - NIST-800-53-CM-6(a)
      - NIST-800-53-CM-7(a)
      - NIST-800-53-CM-7(b)
      - PCI-DSS-Req-2.2.4
      - PCI-DSSv4-2.2.6
      - high_severity
      - low_complexity
      - low_disruption
      - no_reboot_needed
      - restrict_strategy
      - sshd_disable_empty_passwords

##
- name: Disable SSH Support for .rhosts Files
  block:
    - name: Disable SSH Support for .rhosts Files
      block:

      - name: Check for duplicate values
        lineinfile:
          path: /etc/ssh/sshd_config
          create: true
          regexp: (?i)^\s*IgnoreRhosts\s+
          state: absent
        check_mode: true
        changed_when: false
        register: dupes

      - name: Deduplicate values from /etc/ssh/sshd_config
        lineinfile:
          path: /etc/ssh/sshd_config
          create: true
          regexp: (?i)^\s*IgnoreRhosts\s+
          state: absent
        when: dupes.found is defined and dupes.found > 1

      - name: Insert correct line to /etc/ssh/sshd_config
        lineinfile:
          path: /etc/ssh/sshd_config
          create: true
          regexp: (?i)^\s*IgnoreRhosts\s+
          line: IgnoreRhosts yes
          state: present
          insertbefore: BOF
          validate: /usr/sbin/sshd -t -f %s
      when: ansible_virtualization_type not in ["docker", "lxc", "openvz", "podman", "container"]
      tags:
      - CCE-80899-8
      - CJIS-5.5.6
      - NIST-800-171-3.1.12
      - NIST-800-53-AC-17(a)
      - NIST-800-53-CM-6(a)
      - NIST-800-53-CM-7(a)
      - NIST-800-53-CM-7(b)
      - PCI-DSSv4-2.2.6
      - low_complexity
      - low_disruption
      - medium_severity
      - no_reboot_needed
      - restrict_strategy
      - sshd_disable_rhosts

##
# - name: Disable SSH Root Login
#   block:
#     - name: Disable SSH Root Login
#       block:

#       - name: Check for duplicate values
#         lineinfile:
#           path: /etc/ssh/sshd_config
#           create: true
#           regexp: (?i)^\s*PermitRootLogin\s+
#           state: absent
#         check_mode: true
#         changed_when: false
#         register: dupes

#       - name: Deduplicate values from /etc/ssh/sshd_config
#         lineinfile:
#           path: /etc/ssh/sshd_config
#           create: true
#           regexp: (?i)^\s*PermitRootLogin\s+
#           state: absent
#         when: dupes.found is defined and dupes.found > 1

#       - name: Insert correct line to /etc/ssh/sshd_config
#         lineinfile:
#           path: /etc/ssh/sshd_config
#           create: true
#           regexp: (?i)^\s*PermitRootLogin\s+
#           line: PermitRootLogin no
#           state: present
#           insertbefore: BOF
#           validate: /usr/sbin/sshd -t -f %s
#       when: ansible_virtualization_type not in ["docker", "lxc", "openvz", "podman", "container"]
#       tags:
#       - CCE-80901-2
#       - CJIS-5.5.6
#       - DISA-STIG-RHEL-08-010550
#       - NIST-800-171-3.1.1
#       - NIST-800-171-3.1.5
#       - NIST-800-53-AC-17(a)
#       - NIST-800-53-AC-6(2)
#       - NIST-800-53-CM-6(a)
#       - NIST-800-53-CM-7(a)
#       - NIST-800-53-CM-7(b)
#       - NIST-800-53-IA-2
#       - NIST-800-53-IA-2(5)
#       - PCI-DSS-Req-2.2.4
#       - PCI-DSSv4-2.2.6
#       - low_complexity
#       - low_disruption
#       - medium_severity
#       - no_reboot_needed
#       - restrict_strategy
#       - sshd_disable_root_login

##
- name: Disable SSH TCP Forwarding
  block:
    - name: Disable SSH TCP Forwarding
      block:

      - name: Check for duplicate values
        lineinfile:
          path: /etc/ssh/sshd_config
          create: true
          regexp: (?i)^\s*AllowTcpForwarding\s+
          state: absent
        check_mode: true
        changed_when: false
        register: dupes

      - name: Deduplicate values from /etc/ssh/sshd_config
        lineinfile:
          path: /etc/ssh/sshd_config
          create: true
          regexp: (?i)^\s*AllowTcpForwarding\s+
          state: absent
        when: dupes.found is defined and dupes.found > 1

      - name: Insert correct line to /etc/ssh/sshd_config
        lineinfile:
          path: /etc/ssh/sshd_config
          create: true
          regexp: (?i)^\s*AllowTcpForwarding\s+
          line: AllowTcpForwarding no
          state: present
          insertbefore: BOF
          validate: /usr/sbin/sshd -t -f %s
      when: ansible_virtualization_type not in ["docker", "lxc", "openvz", "podman", "container"]
      tags:
      - CCE-83301-2
      - PCI-DSSv4-2.2.6
      - low_complexity
      - low_disruption
      - medium_severity
      - no_reboot_needed
      - restrict_strategy
      - sshd_disable_tcp_forwarding